#Script for reading output files generated by 'Streamflow_Depletion_Accretion.R' for each depletion/accretion cell

# Initialize Script -------------------------------------------------------
library(dplyr)
library(sf)
args = commandArgs(trailingOnly = TRUE)
if(!grepl(x = args[1], pattern = 'Depletion|Accretion', ignore.case = F) ){
  stop("'Depletion' or 'Accretion' (case sensitive) must be supplied as an argument")
}
cell_type = args[1]
cell_type_abv = strtrim(cell_type,3)
pumping_rate = as.numeric(args[2])  #pumping or recharge rate

# User Input --------------------------------------------------------------
dep_acc_cells = read.table('./SVIHM/SWBM_depletion_accretion/input/depletion_accretion_cells.txt', header = T)
monthly_files = list.files(path = paste0('./',cell_type,'_Results/'), pattern = 'Monthly',full.names = T)   
daily_files = list.files(path = paste0('./',cell_type,'_Results/'), pattern = 'Daily')
nstress = 252      #number of stress periods
model_months = format(seq(as.Date('1990-10-01'),length.out = 252, by = 'month'),'%b%y')

# Read Data ---------------------------------------------------------------
#create vector of order that files are read in
monthly_file_order = substring(monthly_files,41)
monthly_file_order = as.numeric(substring(monthly_file_order, 1, nchar(monthly_file_order)-4))

Monthly_Data = lapply(monthly_files, FUN = function(x) read.table(x,header = T))
row_idx = dep_acc_cells$row[monthly_file_order]      #Populate row number in order that the files are read in
col_idx = dep_acc_cells$column[monthly_file_order]   #Populate col number in order that the files are read in
locs = data.frame(row = row_idx, column = col_idx)
locs = left_join(locs,dep_acc_cells[,-1], by = c('row','column') )
MB_Fail_pct = rep(NaN, 252)       # create emply array for percentage of pumping/recharge cells that fail the mass balance
# Create Monthly Rasters --------------------------------------------------
for (i in 1:nstress){
  locs$BC_FJ_flow = sapply(Monthly_Data, "[[", 2)[i,]
   locs$del_S = sapply(Monthly_Data, "[[", 3)[i,]
  locs$del_pump = sapply(Monthly_Data, "[[", 4)[i,]
  locs$del_ET = sapply(Monthly_Data, "[[", 5)[i,]
  locs$del_drns = sapply(Monthly_Data, "[[", 6)[i,]
  locs$FJ_delQ = sapply(Monthly_Data, "[[", 7)[i,]
  locs$del_GWSW = sapply(Monthly_Data, "[[", 8)[i,]
  locs$BCdrySR_m = sapply(Monthly_Data, "[[", 9)[i,]
  locs$BCdryTrb_m = sapply(Monthly_Data, "[[", 10)[i,]
  locs$BCdryAll_m = sapply(Monthly_Data, "[[", 11)[i,]
  locs$BCdrySRnmm = sapply(Monthly_Data, "[[", 12)[i,]
  locs$BCdryTrbnm = sapply(Monthly_Data, "[[", 13)[i,]
  locs$BCdryAllnm = sapply(Monthly_Data, "[[", 14)[i,]
  locs$MassB_pct = sapply(Monthly_Data, "[[", 15)[i,]
  locs$FJFlwRdPct = abs(locs$FJ_delQ / locs$BC_FJ_flow)*100
  locs$StrmFlwDep = locs$FJ_delQ / pumping_rate

  point.sf = st_as_sf(locs, coords = c('UTM_E', 'UTM_N'), crs = 26910)   #Convert dataframe to shapefile (UTM Zone 10 NAD1983)
  st_write(obj = point.sf, dsn = paste0('../../Streamflow_Depletion_GIS/Shapefiles/',cell_type,'/',cell_type_abv,'_',model_months[i],'.shp'), delete_dsn = T)
  MB_Fail_pct[i] = (length(locs$del_S[is.na(locs$del_S)])/712)*100
  
}

